/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ClienteDao;
import dao.LivroDao;
import dao.VendaDao;
import model.Livro;

/**
 *
 * @author Daniel
 */
public class FormPrincipal extends javax.swing.JFrame {
    public static ClienteDao dbCliente;
    public static LivroDao dbLivro;
    public static VendaDao dbVenda = null;
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        dbCliente = new ClienteDao();
        dbLivro = new LivroDao();
        dbVenda = new VendaDao();
        initComponents();
        this.cadastrarLivros();
    }
    
    public void cadastrarLivros()
    {
        Livro livro = null; //criando um livro
        for(int i=1; i<30; i++) // serão acrescentados 30 livros na base
        {
            livro = new Livro();                    
            livro.setCodigo(Integer.toString(1000+i));
            livro.setTitulo("Livro com Titulo " + i);
            livro.setFornecedor("Editora " + i+10);
            livro.setQuantidadeEstoque((int)(Math.random() * 10)+ 10*i);
            livro.setValorUnitario((50%i) + (i*10));            
            livro.setDataPublicação(i+"/05/"+(1990+i));
            FormPrincipal.dbLivro.adicionarLivro(livro); //adicionando um livro genérico na base
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuLivro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuLivros = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenuDia = new javax.swing.JMenuItem();
        jMenuMes = new javax.swing.JMenuItem();
        jMenuAno = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuNovaVenda = new javax.swing.JMenuItem();
        jMenuEmitirNF = new javax.swing.JMenuItem();
        jMenuSuporte = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle da Livraria Livro Aberto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosActionPerformed(evt);
            }
        });

        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/inserirCliente.png"))); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCliente);

        jMenuLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/livro.png"))); // NOI18N
        jMenuLivro.setText("Livro");
        jMenuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLivroActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuLivro);
        jMenuCadastros.add(jSeparator1);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/sair.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuSair);

        jMenuBar1.add(jMenuCadastros);

        jMenuConsultas.setText("Consultas");

        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/inserirCliente.png"))); // NOI18N
        jMenuClientes.setText("Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuClientes);

        jMenuLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/livro.png"))); // NOI18N
        jMenuLivros.setText("Livros");
        jMenuLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLivrosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuLivros);

        jMenuCompras.setText("Compras");

        jMenuDia.setText("Dia");
        jMenuCompras.add(jMenuDia);

        jMenuMes.setText("Mês");
        jMenuCompras.add(jMenuMes);

        jMenuAno.setText("Ano");
        jMenuCompras.add(jMenuAno);

        jMenuConsultas.add(jMenuCompras);

        jMenuBar1.add(jMenuConsultas);

        jMenuVendas.setText("Vendas");

        jMenuNovaVenda.setText("Nova Venda");
        jMenuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovaVendaActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuNovaVenda);

        jMenuEmitirNF.setText("Emitir N.F.");
        jMenuVendas.add(jMenuEmitirNF);

        jMenuBar1.add(jMenuVendas);

        jMenuSuporte.setText("Suporte");

        jMenuAjuda.setText("Ajuda");
        jMenuSuporte.add(jMenuAjuda);
        jMenuSuporte.add(jSeparator2);

        jMenuSobre.setText("Sobre");
        jMenuSuporte.add(jMenuSobre);

        jMenuBar1.add(jMenuSuporte);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(808, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        new FormCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosActionPerformed
        new FormCliente().setVisible(true);
    }//GEN-LAST:event_jMenuCadastrosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed
        new FormBuscaCliente().setVisible(true);
    }//GEN-LAST:event_jMenuClientesActionPerformed

    private void jMenuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLivroActionPerformed
        new FormLivro().setVisible(true);
    }//GEN-LAST:event_jMenuLivroActionPerformed

    private void jMenuLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLivrosActionPerformed
        new FormBuscaLivro().setVisible(true);
    }//GEN-LAST:event_jMenuLivrosActionPerformed

    private void jMenuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovaVendaActionPerformed
        new FormVenda().setVisible(true);
    }//GEN-LAST:event_jMenuNovaVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAjuda;
    private javax.swing.JMenuItem jMenuAno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuDia;
    private javax.swing.JMenuItem jMenuEmitirNF;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuLivro;
    private javax.swing.JMenuItem jMenuLivros;
    private javax.swing.JMenuItem jMenuMes;
    private javax.swing.JMenuItem jMenuNovaVenda;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JMenu jMenuSuporte;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
