/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Livro;

/**
 *
 * @author Daniel
 */
public class FormBuscaLivro extends javax.swing.JFrame {
    
    DefaultTableModel modelo = null;
    /**
     * Creates new form FormBuscaLivro
     */
    public FormBuscaLivro() {
        initComponents();
        modelo = (DefaultTableModel) tbLivros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ftCodigo = new javax.swing.JFormattedTextField();
        btBuscar = new javax.swing.JButton();
        cbBuscaTodos = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLivros = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Código");

        try {
            ftCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCodigo.setName("ftCodigo"); // NOI18N
        ftCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftCodigoKeyReleased(evt);
            }
        });

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/icBuscar.png"))); // NOI18N
        btBuscar.setText("Buscar Livro");
        btBuscar.setEnabled(false);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        cbBuscaTodos.setText("Buscar Todos");
        cbBuscaTodos.setName("cbBuscaTodos"); // NOI18N
        cbBuscaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscaTodosActionPerformed(evt);
            }
        });

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/icAtualizar.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/icExcluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/icSair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel1.add(btSair);

        tbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Fornecedor", "Quantidade", "Valor Unitário", "Data de Publicação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLivros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbLivros.setColumnSelectionAllowed(true);
        tbLivros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tbLivros);
        tbLivros.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbLivros.getColumnModel().getColumnCount() > 0) {
            tbLivros.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbLivros.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbLivros.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbLivros.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbLivros.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbLivros.getColumnModel().getColumn(5).setPreferredWidth(130);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbBuscaTodos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBuscar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBuscaTodos)))
                    .addComponent(btBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        setSize(new java.awt.Dimension(454, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        limparTabela();
        
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        if(cbBuscaTodos.isSelected()){
            List<Livro> lista = FormPrincipal.dbLivro.todosLivros();
            for(Livro l: lista){
                inserirLivro(l);
                btEditar.setEnabled(true);
                btExcluir.setEnabled(true);
            }
            if(modelo.getRowCount() == 0){
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Não existem livros cadastrados!", "Erro pesquisa", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            Livro l = FormPrincipal.dbLivro.buscarLivro(ftCodigo.getText());
            if(l != null){
                inserirLivro(l);
                btEditar.setEnabled(true);
                btExcluir.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Não existe livro cadastrado com esse código!", "Erro pesquisa", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void cbBuscaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscaTodosActionPerformed
        if(cbBuscaTodos.isSelected()){
            btBuscar.setEnabled(true);
            ftCodigo.setEnabled(false);
        }else{
            ftCodigo.setEnabled(true);
            String aux = ftCodigo.getText();
            aux = aux.replace(" ", "");
            if(aux.length() < 5){
                btBuscar.setEnabled(false);
            }else{
                btBuscar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cbBuscaTodosActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void ftCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftCodigoKeyReleased
        String aux = ftCodigo.getText();
        aux = aux.replace(" ", "");
        if(aux.length() < 5){
            btBuscar.setEnabled(false);
        }else{
            btBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_ftCodigoKeyReleased

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        Livro l = getLivro();
        if(l != null){
            FormLivro.setLivro(l);
            new FormLivro().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Não existe livro cadastrado com esse código!", "Erro pesquisa", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Object[] options = {"Sim", "Não"};
        if(JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION){
            int linha = tbLivros.getSelectedRow();
            String str = (String) tbLivros.getModel().getValueAt(linha, 1);
            FormPrincipal.dbLivro.removerLivro(str);
            JOptionPane.showMessageDialog(null, "Livro excluído com sucesso!", "Livro Excluído", JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel modelo = (DefaultTableModel) tbLivros.getModel();
            modelo.removeRow(linha);
            if(modelo.getRowCount() == 0){
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                ftCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void limparTabela(){
        for (int i = tbLivros.getRowCount() - 1; i >= 0; --i){
            modelo.removeRow(i);
        }
    }
    
    private void inserirLivro(Livro l){
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        String aux = f.format(l.getDataPublicação());
        modelo.addRow(new Object[]{l.getCodigo(), l.getTitulo(), l.getFornecedor(), l.getQuantidadeEstoque(), l.getValorUnitario(), aux});
    }
    
    private Livro getLivro(){
        int linha = tbLivros.getSelectedRow();
        String str = (String) tbLivros.getModel().getValueAt(linha, 0);
        Livro l = FormPrincipal.dbLivro.buscarLivro(str);
        return l;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuscaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuscaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuscaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuscaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuscaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox cbBuscaTodos;
    private javax.swing.JFormattedTextField ftCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbLivros;
    // End of variables declaration//GEN-END:variables
}
